### ISSUE TITLE
Add minitest to gemspec

### ISSUE THREAD

**Issue by bkabrda** [rails/prototype-rails#13]
Hi,
I think you should add minitest or test/unit to the gemspec. When using with Fedora Ruby with unbundled minitest, I get 
cannot load such file -- minitest/unit
...
/home/bkabrda/.gem/ruby/1.9.1/gems/prototype-rails-3.2.1/lib/prototype-rails/on_load_action_view.rb:17:in `<top (required)>'
...
Thanks!

**Comment by dylanahsmith** [comment]
> I think you should add minitest or test/unit to the gemspec.

I disagree, I think prototype-rails should avoid autoloading minitest.  This is what pull request #23 does, which I think would also address your issue.

**Comment by rafaelfranca** [comment]
RIght
