### ISSUE TITLE
`require': cannot load such file -- action_view/vendor/html-scanner (LoadError)

### ISSUE THREAD

**Issue by kddeisz** [rails/prototype-rails#37]
Seems like I can't upgrade to Rails 4.2 while using prototype-rails. I've tried using the deprecated sanitizer gem (gem 'rails-deprecated_sanitizer', '~> 1.0.3') but that hasn't fixed the load error. I know this isn't technically supported, but is there any way this is fixable?

**Comment by shibabu** [comment]
Same here, the solution was to put this line instead in the Gemfile:
gem 'prototype-rails', github: 'rails/prototype-rails', branch: '4.2'

**Comment by kddnewton** [comment]
Thanks @shibabu
