### ISSUE TITLE
flash message not displaying while using the rcs

### ISSUE THREAD

**Issue by NeelaveniT** [rails/prototype-rails#42]
Hi,
rcs file is loaded,but the flash message is not loaded properly.
The content of the rcs file is below

#page['ajax-indicator'].set_style :display => ''
data = @data || :data
output = @output || :output
#page.alert(page[:subject_form])
#page[:subject_form].reset()
if @successful
  page[data].replace_html :partial => @partial_render
  page[output].replace_html flash_messages
else
  if(flash[:notice] or flash[:error])
    page[output].replace_html flash_messages
  else
    page[output].replace_html error_messages_for @model
  end
end

#page.visual_effect :fade, 'ajax-indicator'
#page['ajax-indicator'].set_style :display => 'none'

The output for adding I got as follow

$("data").update("\n\u003cp class='info'\u003eNo data to display\u003c/p\u003e\n\n");
$("output").update("\u003cp class='success'\u003eNew activity is added successfully\u003c/p\u003e\u003cbr\u003e");
new Effect.Fade("ajax-indicator",{});

But I want this output with flash with appropriate image.

Kindly help me to resolve this issue.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
