### ISSUE TITLE
cannot load such file -- action_view/vendor/html-scanner (LoadError)

### ISSUE THREAD

**Issue by harika396** [rails/prototype-rails#43]
Hello,
I am upgrading rails application to 4.2 and i am facing **html-scanner** issue when attempting to start the webrick server.
 I found that the issue is causing with prototype-rails gem from other blogs and I tried updating my Gemfile with below line. 
gem 'prototype-rails', github: 'rails/prototype-rails', branch: '4.2'
After I add this line, bundle install and restart the server, server starts fine but none of the assets are loading in the UI when I navigate to localhost:3000.
Any suggestions on this issue would be appreciated!!

Below is some more details of the error
=> Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- action_view/vendor/**html-scanner** (LoadError)
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/prototype-rails-4.0.0/lib/prototype-rails/selector_assertions.rb:2:in `<top (required)>'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/prototype-rails-4.0.0/lib/prototype-rails/on_load_action_controller.rb:1:in `<top (required)>'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/prototype-rails-4.0.0/lib/prototype-rails.rb:8:in `block (2 levels) in <class:Engine>'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/prototype-rails-4.0.0/lib/prototype-rails.rb:7:in `block in <class:Engine>'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/user123/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
........

**Comment by rafaelfranca** [comment]
You also need https://github.com/rails/rails-deprecated_sanitizer in your application.
